# Generated by Django 3.0.7 on 2021-04-20 12:02

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='comment',
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='GBP', max_digits=4, null=True),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
