# Generated by Django 3.0.7 on 2020-06-18 14:33

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20200618_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='GBP', max_digits=3, null=True),
        ),
    ]
